version: "3"

services:
  api:
    env_file: .env
    container_name: api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=${APP_DIR}
    volumes:
      - './:${APP_DIR}'
      - ${APP_DIR}/node_modules/
    command: npm run watch
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on: 
      - db
    
  db:
    image: postgres
    container_name: db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter 
    ports:
      - ${ADMINER_PORT}:8080
    logging:
      driver: none