export const TABLE_NAMES = {
	ARCHIVE_VIDEO_LOGS : "archive_video_logs",
	COURSES : "courses",
	EVENT_CLASSES:"event_classes",
	EVENT_EXTRAS:"event_extras",
	EVENT_MESSAGES:"event_messages",
	EVENT_REGISTERS:"event_registers",
	EVENT_TYPES:"event_types",
	EVENTS:"events",
	EXAMS:"exams",
	GRADES:"grades",
	GROUP_COURSES:"group_courses",
	HOLIDAYS:"holidays",
	J_CATEGORIES:"j_categories",
	J_TAGS:"j_tags",
	JOURNAL_CATEGORIES:"journal_categories",
	JOURNAL_TAGS:"journal_tags",
	JOURNALS:"journals",
	KNEX_MIGRATIONS:"knex_migrations",
	KNEX_MIGRATIONS_LOCK:"knex_migrations_lock",
	LOGS:"logs",
	NOTIFICATIONS:"notifications",
	PARTICIPATION:"participation",
	PERMISSIONS:"permissions",
	PRIVATE_DOCUMENT_TYPES:"private_document_types",
	PRIVATE_DOCUMENTS:"private_documents",
	PRIVATE_TASKS:"private_tasks",
	ROLE_PERMISSIONS:"role_permissions",
	ROOM_TYPES:"room_types",
	ROOMS:"rooms",
	SEMESTERS:"semesters",
	TASK_COMMENTS:"task_comments",
	TASK_UPLOADS:"task_uploads",
	TASKS:"tasks",
	TICKET_MESSAGES:"ticket_messages",
	TICKET_UPLOADS:"ticket_uploads",
	TICKETS:"tickets",
	VIDEO_ARCHIVES:"video_archives",
    USERS: "users",
    GROUPS: "groups",
    ROLES: "roles",
    USER_STUDENTS: "user_students",
    USER_TEACHERS: "user_teachers",
    USER_AFFAIRS: "user_affairs",
    USER_VERIFICATION_CODES: "user_verification_codes"
}